language: swift
osx_image: xcode8

language: swift
osx_image: xcode8

install:
  - gem install xcpretty

script: 
  - xcodebuild -project FaveButtonDemo/SparkImageView.xcodeproj  -scheme "FaveButtonDemo" -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s' | xcpretty
